### ISSUE TITLE
Can I get the the class of point cloud through lidar-synthesis?

### ISSUE THREAD

**Issue by rockywind** [jonathsch/lidar-synthesis#1]

**Comment by jonathsch** [comment]
Hi @rockywind,

Could you clarify what you mean by "class of point cloud"?

**Comment by rockywind** [comment]
Hi, @jonathsch 
Sorry for that. I mean can I get the point cloud's label, such as, vehicle, road and etc.

**Comment by jonathsch** [comment]
Thanks for the clarification,

No. Currently, the framework does not generate semantic labels for the point cloud.

**Comment by rockywind** [comment]
Hi, 
if I want to generate the semantic labels for the point cloud, there are any suggest?
